### ISSUE TITLE
Create raw Command/Response

### ISSUE THREAD

**Issue by serianox** [GPSecretariat/WebApis-for-se#13]
As it is possible to send/receive raw APDU encoded as `UInt8Array`, there may be a need to be able to create from or convert to these.

``` webidl
[Constructor(octet cla, octet ins, octet p1, octet p2, optional Uint8Array data, optional octet le),
 Constructor(Uint8Array raw)]
interface SECommand {
             attribute octet          cla;
             attribute octet          ins;
             attribute octet          p1;
             attribute octet          p2;
             attribute Uint8Array?    data;
             attribute unsigned short le;
    readonly attribute Uint8Array     raw;
};
```

``` webidl
[Constructor(Uint8Array raw)]
interface SEResponse {
    readonly attribute Channel    channel;
    readonly attribute octet      sw1;
    readonly attribute octet      sw2;
    readonly attribute Uint8Array data;
    readonly attribute Uint8Array raw;
    boolean isStatus (octet? sw1, octet? sw2);
};
```

**Comment by opoto** [comment]
There is no need to construct a SECommand from raw bytes, as one can directly send raw bytes using transmitRaw method.
There is actually no need to expose a constructor for SEResponse at all, as it is constructed by the underlying API implementation. This will be removed from API.

**Comment by opoto** [comment]
The reason we introduced the constructor for the response is to provide access to the isStatus() method for raw responses. So we can keep it as it is currently specified.
