### ISSUE TITLE
Incorrect description of parameter 'p2' in openBasicChannel

### ISSUE THREAD

**Issue by serianox** [GPSecretariat/WebApis-for-se#19]
In subsection 11.2, for the description of `openBasicChannel`:

> The device should allow all values for P2, however only the following values are mandatory: ‘00’, ‘04’, ‘08’, ‘0C’

Since occurrence selection is done by the WebApi, `b2` and `b1` can not be chosen by the web application. Only `b3` and `b4` can. `b8` through `b5` are RFU and must be set to zero. Thus the wording is incorrect, it should be _allowed_ instead of _mandatory_.

> The device should allow all values for P2, however only the following values are allowed: ‘00’, ‘04’, ‘08’, ‘0C’

Also, this wording is still not future-proof.

There is the same issue for `openSupplementaryChannel`.

**Comment by opoto** [comment]
Will be rephrased
