### ISSUE TITLE
Use Model

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#21]
### Comments from Trusted Computing Group - Item # 2

**Section:** 1.2

**Comment:** Actual usage model should be specified here.  Is the intent that ordinary users will physically move UICC cards among multiple mobile devices?  This is not practical in most cases.  Does this off-card web application on the same mobile device where the UICC is present or on some remote system?

**Proposed Resolution:** Specify use model.

**Comment by opoto** [comment]
The model is defined in previous section: "Technical background".
UICC is not supposed to be moved, and the client part of the web application (= off-card application) is running on the device where secure element is present.
