### ISSUE TITLE
Access Control Enforcer

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#33]
### Comments from Trusted Computing Group - Item # 14

**Section:** 6.1 Overall Architecture

**Comment:** Re “An Access Control Enforcer is running on the same device as the off-card application.”

**Proposed Resolution:** It appears that a compromised Requesting application could compromise the access control enforcer.  How would this be implemented?  Or is the figure wrong?  Is the Access Control Enforcer in the kernel?  Shouldn't it be higher privilege than the application?

**Comment by serianox** [comment]
I don't have access to the [GP-AC] currently, but I assume from the drawing that the Access Control Enforcer is separated from the Requesting Application through _process isolation_, _sandbox_ or any similar mechanism.

**Comment by opoto** [comment]
Yes, the Access Control Enforcer is defined in GP-AC. Please refer to this specification for more information about it.
