### ISSUE TITLE
isRemovable and hot-swap vs power-down

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#39]
### Comments from Trusted Computing Group - Item # 20

**Section:** 10.1 Attributes

**Comment:** Re: “isRemovable of type boolean, readonly
This attribute MUST return true if the Secure Element cannot be detached without powering down the device.”

**Proposed Resolution:** What does "isRemovable" have to do with hot-swap versus power-down for removal of an SE?

**Comment by opoto** [comment]
"isRemovable" is similar to hot-swap, however "isHotSwappable" would not be appropriate.
