### ISSUE TITLE
Byte ordering

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#51]
### Comments from Trusted Computing Group - Item # 32

**Section:** WebIDL

**Comment:** Re “attribute Uint8Array data;” 

**Proposed Resolution:** Is byte ordering discussed in this document?

**Comment by serianox** [comment]
Byte ordering (aka _endianess_) is irrelevant in ISO 7816-4. All data structure are defined as a sequence of 8-bits bytes.

It could be compared to some extent to network byte order.
