### ISSUE TITLE
Terms "error' and "exception" are mixed

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#52]
### Comments from Trusted Computing Group - Item # 33

**Section:** 15. Error Types

**Comment:** The terms "error" and "exception" should be differentiated.  They seem to be mixed in this document.

**Proposed Resolution:**

**Comment by opoto** [comment]
The specification only uses the term "error" to designate the data returned when an operation fails. However because error types inherit from DOMException, we named them using the "exception" suffix.
