### ISSUE TITLE
Granularity of Error Responses

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#54]
### Comments from Trusted Computing Group - Item # 35

**Section:** SESecurityException

**Comment:** There should be more granularity in the error response. 

**Proposed Resolution:** What types of mismatch occurred?  Insufficient privilege?  Is an unknown object a security exception or an IO exception?

**Comment by opoto** [comment]
SESecurityException is raised when access conditions are not met. The application should not be informed about those access conditions, this would unnecessarily leak security related information.
