### ISSUE TITLE
Granularity of SEIoException

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#55]
### Comments from Trusted Computing Group - Item # 36

**Section:** SEIoException

**Comment:** There should be finer granularity in this type as well.

**Proposed Resolution:**

**Comment by opoto** [comment]
Application has no control over IO communications, so it would probably not benefit from additional information. However the optional "message" field (inherited from DOMException) may be used to convey a user readable cause that could help user to fix the problem.
