### ISSUE TITLE
SEClosedException is an IO exception

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#57]
### Comments from Trusted Computing Group - Item # 38

**Section:** SENoChannelException

**Comment:** Re: “SEClosedException
The operation could not be fulfilled because the target object is closed” 

**Proposed Resolution:** Isn't this an IO exception?

**Comment by opoto** [comment]
The objective of SEClosedException is to provide a more accurate information for this very usual error.
