### ISSUE TITLE
SEClosedException is a state exception

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#58]
### Comments from Trusted Computing Group - Item # 39

**Section:** SEClosedException

**Comment:** Re: “SEClosedException
The operation could not be fulfilled because the target object is closed”  

**Proposed Resolution:** Isn't this a state exception?

**Comment by opoto** [comment]
The objective of SEClosedException is to provide a more accurate information for this very usual error.
