### ISSUE TITLE
Dead links to GitHub repositories and Issues

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#60]
### Comments from Trusted Computing Group - Item # 41

**Section:** A. Changes

**Comment:** Re: “The complete list of changes can be viewed on Github. You can also check the issues.”

**Proposed Resolution:** These are not live links.

**Comment by opoto** [comment]
These links are working on the web versions of the [public review](https://globalplatform.github.io/WebApis-for-SE/doc/public-review.html) release and the [latest draft](http://globalplatform.github.io/WebApis-for-SE/doc/)
