### ISSUE TITLE
How can i access SE from firefox??

### ISSUE THREAD

**Issue by meriabdou** [GPSecretariat/WebApis-for-se#62]
HI,I read the specifications of the API SE but I do not know how to integrate this API in a concrete example, what does it miss? is there a description setp y step to at least list the readers connected to the PC ?? please I'm stuck at this level thanks for any help

**Comment by opoto** [comment]
Hello
If your question is about API usage, you can find an example here: http://globalplatform.github.io/WebApis-for-SE/doc/#code-example
If your question is about actual implementation, this API has not been implemented in any commercial browser as of today. 
If you want to use it in a browser, you need to implement the API at application level: a javascript that would communicate with a smard card though an out-of-the-browser mechanism, such as using a local web-socket server that would provide a proxy to a smart card through PC/SC on a desktop, or OMAPI on a mobile.
Hopefully this API will natively be available in browsers someday.
