### ISSUE TITLE
Rrelationship between the proposed Web API and SIMalliance’s OMAPI

### ISSUE THREAD

**Issue by hchavers** [GPSecretariat/WebApis-for-se#9]
Hi

Quick introduction: I work for UL, mainly on UICC and NFC-related technologies. I participate in the GSMA NFC handset groups, which references SIMalliance’s OMAPI.

My main question is about any relationship between the proposed Web API and SIMalliance’s OMAPI. A quick comparison of the APIs shows that they are very similar, with only minor differences (and possibly some small improvements). The Web API may have the advantage of being defined in WebIDL, making its usage more natural for web applications.
Was any consideration given to more directly reusing the OMAPI – for example, by defining a mapping for web applications? Both APIs are addressing a very similar domain.

One particular point to note is that there have been some evolutions of the OMAPI due to issues that have been identified – primarily with T=0 and Get Response handling. In OMAPI v3.2, a “Channel.setTransmitBehaviour()” method has been added to deal with the different Get Response requirements of different applications. This subtlety doesn’t seem to currently be dealt with in the Web API. The OMAPI has had more time to mature.
This is a example of two different solutions to the same problem, and being slightly divergent in the approaches and in the coverage of subtle issues such as this one.

A couple of points related to the reference to OMAPI in section 7.2:
• No specific version of OMAPI is referenced, and OMAPI is not included in the references in Annex B.
• The wording in the initial sentence doesn’t seem to be quite correct, as it doesn’t actually clearly indicate requirements on the Web API. It is currently just an (incorrect) statement about OMAPI: “OMAPI requires …”.
For example, I would suggest: “… all the methods defined in this document shall follow the management of status words specified in SIMalliance OMAPI, as indicated below:”

Thanks,
Calum

**Comment by serianox** [comment]
Hi Hank,

I'm still trying to understand what is setTransmitBehavior trying to achieve. After reading through ISO 7816-3, -4 and OMAPI 3.2, this is still really unclear to me. Do you have any use case where different behavior have impact on the application?

In any case, the whole chapter 7 deals with considerations on mapping APDU to the underlying transport layer. I don't think we should keep this as the WebApi does specify the applicative layer, i.e. 7816-4, and also we would need one section for each existing or future transport layer for ISO APDUs.

Is there any way we could make this transport specificity transparent to the application?

**Comment by hchavers** [comment]
Email response sent to original contributor:

Dear Calum MacLean,

We appreciate your review of the Web API for Accessing the SE specification.

The work on the Web access for OMAPI originated in the W3C which was contributed to and reference by SIMalliance.  The W3C has archived this specification and GlobalPlatform has continued the work.  

Here is our responses to your comments below:
-   Channel.setTransmitBehaviour() is not needed as the WEB API does to specify the applicable layer
-   The OMAPI references has been removed

Please let us know if you have any further comments or questions.  The specification updates can be reviewed at the GitHub project at https://github.com/GlobalPlatform/WebApis-for-SE. 

(T)Hank(s)

**Comment by hchavers** [comment]
No response received from the original contributor.  Closing the issue.
